name: CI

on:
  push:
    branches: [main]
    tags: ["releases/**"]
  pull_request:
    branches: ["*"]

jobs:
  python:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: 3.8
      - run: uv sync --frozen
      - run: uv run black --check --diff --color --extend-exclude '.*_pb2.py' .
      - run: uv run pyright foxglove
      - run: uv run python -m flake8 foxglove
      - run: uv run python -m flake8 examples
      - run: uv run python -m pytest
      - run: uv run python -m build

      - name: Publish to TestPyPI
        if: |
          !github.event.pull_request.head.repo.fork &&
          github.actor != 'dependabot[bot]'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          attestations: false # https://github.com/pypa/gh-action-pypi-publish/issues/283#issuecomment-2499296440

      - name: Publish to PyPI
        if: |
          !github.event.pull_request.head.repo.fork &&
          startsWith(github.ref, 'refs/tags/releases/v')
        uses: pypa/gh-action-pypi-publish@unstable/v1
        with:
          packages-dir: dist
